project_id = "brainy-backend"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
api_url = "http://localhost:54324"
smtp_port = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"
bucket_id = "quiz-files"

[auth]
enabled = true
port = 54327
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[edge_runtime]
enabled = true
port = 54328

[analytics]
enabled = true
port = 54329
vector_port = 54330
gw_port = 54331

[functions.quiz-data]
verify_jwt = true

[functions.auth-enhanced]
verify_jwt = false

[functions.sync-progress]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true

[functions.health]
verify_jwt = false 